name: Django CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
    
        runs-on: ubuntu-latest
    
        steps:
        - name: Checar o código
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'

    
        - name: Instalar as dependências
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install django
        
        - name: Rodar os testes
          run: |
            python manage.py test
        
